; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
board_build.filesystem = littlefs
build_flags = 
    -Os                                 ; Optimize for size
    -DCORE_DEBUG_LEVEL=0               ; Disable debug output
    -ffunction-sections                 ; Place each function in its own section
    -fdata-sections                     ; Place each data item in its own section
build_unflags = -Os -O2 -O3
board_build.partitions = min_spiffs.csv ; Use minimal SPIFFS partition
lib_deps = 
	plerup/EspSoftwareSerial@^8.2.0
	enjoyneering/AHT10@^1.1.0
	adafruit/ENS160 - Adafruit Fork@^3.0.1
	paulvha/sps30@^1.4.17
	adafruit / Adafruit GPS Library @^1.7.5
	ESP32Async/ESPAsyncWebServer @ 3.6.0
	arduino-libraries/Arduino_JSON @ 0.1.0
	ESP32Async/AsyncTCP @ 3.3.2
	robtillaart/RunningMedian@^0.3.9
	bblanchon/ArduinoJson@^7.4.0
